// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ATan2Options struct {
	_tab flatbuffers.Table
}

func GetRootAsATan2Options(buf []byte, offset flatbuffers.UOffsetT) *ATan2Options {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ATan2Options{}
	x.Init(buf, n+offset)
	return x
}

func FinishATan2OptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsATan2Options(buf []byte, offset flatbuffers.UOffsetT) *ATan2Options {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ATan2Options{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedATan2OptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ATan2Options) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ATan2Options) Table() flatbuffers.Table {
	return rcv._tab
}

func ATan2OptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func ATan2OptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
