// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type BitcastOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsBitcastOptions(buf []byte, offset flatbuffers.UOffsetT) *BitcastOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BitcastOptions{}
	x.Init(buf, n+offset)
	return x
}

func FinishBitcastOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsBitcastOptions(buf []byte, offset flatbuffers.UOffsetT) *BitcastOptions {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &BitcastOptions{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedBitcastOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *BitcastOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BitcastOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func BitcastOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func BitcastOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
