// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type BitwiseXorOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsBitwiseXorOptions(buf []byte, offset flatbuffers.UOffsetT) *BitwiseXorOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BitwiseXorOptions{}
	x.Init(buf, n+offset)
	return x
}

func FinishBitwiseXorOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsBitwiseXorOptions(buf []byte, offset flatbuffers.UOffsetT) *BitwiseXorOptions {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &BitwiseXorOptions{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedBitwiseXorOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *BitwiseXorOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BitwiseXorOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func BitwiseXorOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func BitwiseXorOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
