// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DequantizeOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsDequantizeOptions(buf []byte, offset flatbuffers.UOffsetT) *DequantizeOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DequantizeOptions{}
	x.Init(buf, n+offset)
	return x
}

func FinishDequantizeOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDequantizeOptions(buf []byte, offset flatbuffers.UOffsetT) *DequantizeOptions {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DequantizeOptions{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDequantizeOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DequantizeOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DequantizeOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func DequantizeOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func DequantizeOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
