// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DilateOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsDilateOptions(buf []byte, offset flatbuffers.UOffsetT) *DilateOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DilateOptions{}
	x.Init(buf, n+offset)
	return x
}

func FinishDilateOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDilateOptions(buf []byte, offset flatbuffers.UOffsetT) *DilateOptions {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DilateOptions{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDilateOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DilateOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DilateOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func DilateOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func DilateOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
