// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DynamicUpdateSliceOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsDynamicUpdateSliceOptions(buf []byte, offset flatbuffers.UOffsetT) *DynamicUpdateSliceOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DynamicUpdateSliceOptions{}
	x.Init(buf, n+offset)
	return x
}

func FinishDynamicUpdateSliceOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDynamicUpdateSliceOptions(buf []byte, offset flatbuffers.UOffsetT) *DynamicUpdateSliceOptions {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DynamicUpdateSliceOptions{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDynamicUpdateSliceOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DynamicUpdateSliceOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DynamicUpdateSliceOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func DynamicUpdateSliceOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func DynamicUpdateSliceOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
