// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GatherNdOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsGatherNdOptions(buf []byte, offset flatbuffers.UOffsetT) *GatherNdOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GatherNdOptions{}
	x.Init(buf, n+offset)
	return x
}

func FinishGatherNdOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGatherNdOptions(buf []byte, offset flatbuffers.UOffsetT) *GatherNdOptions {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GatherNdOptions{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGatherNdOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *GatherNdOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GatherNdOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func GatherNdOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func GatherNdOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
