// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GreaterEqualOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsGreaterEqualOptions(buf []byte, offset flatbuffers.UOffsetT) *GreaterEqualOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GreaterEqualOptions{}
	x.Init(buf, n+offset)
	return x
}

func FinishGreaterEqualOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGreaterEqualOptions(buf []byte, offset flatbuffers.UOffsetT) *GreaterEqualOptions {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GreaterEqualOptions{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGreaterEqualOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *GreaterEqualOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GreaterEqualOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func GreaterEqualOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func GreaterEqualOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
