// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type HashtableFindOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsHashtableFindOptions(buf []byte, offset flatbuffers.UOffsetT) *HashtableFindOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &HashtableFindOptions{}
	x.Init(buf, n+offset)
	return x
}

func FinishHashtableFindOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsHashtableFindOptions(buf []byte, offset flatbuffers.UOffsetT) *HashtableFindOptions {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &HashtableFindOptions{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedHashtableFindOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *HashtableFindOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *HashtableFindOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func HashtableFindOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func HashtableFindOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
