// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MatrixSetDiagOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsMatrixSetDiagOptions(buf []byte, offset flatbuffers.UOffsetT) *MatrixSetDiagOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MatrixSetDiagOptions{}
	x.Init(buf, n+offset)
	return x
}

func FinishMatrixSetDiagOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMatrixSetDiagOptions(buf []byte, offset flatbuffers.UOffsetT) *MatrixSetDiagOptions {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MatrixSetDiagOptions{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMatrixSetDiagOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MatrixSetDiagOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MatrixSetDiagOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func MatrixSetDiagOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func MatrixSetDiagOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
