// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RankOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsRankOptions(buf []byte, offset flatbuffers.UOffsetT) *RankOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RankOptions{}
	x.Init(buf, n+offset)
	return x
}

func FinishRankOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRankOptions(buf []byte, offset flatbuffers.UOffsetT) *RankOptions {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RankOptions{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRankOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RankOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RankOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func RankOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func RankOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
