// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import "strconv"

type ReduceWindowFunction int32

const (
	ReduceWindowFunctionUNSUPPORTED ReduceWindowFunction = 0
	ReduceWindowFunctionADD         ReduceWindowFunction = 1
	ReduceWindowFunctionMUL         ReduceWindowFunction = 2
	ReduceWindowFunctionMINIMUM     ReduceWindowFunction = 3
	ReduceWindowFunctionMAXIMUM     ReduceWindowFunction = 4
	ReduceWindowFunctionALL         ReduceWindowFunction = 5
	ReduceWindowFunctionANY         ReduceWindowFunction = 6
)

var EnumNamesReduceWindowFunction = map[ReduceWindowFunction]string{
	ReduceWindowFunctionUNSUPPORTED: "UNSUPPORTED",
	ReduceWindowFunctionADD:         "ADD",
	ReduceWindowFunctionMUL:         "MUL",
	ReduceWindowFunctionMINIMUM:     "MINIMUM",
	ReduceWindowFunctionMAXIMUM:     "MAXIMUM",
	ReduceWindowFunctionALL:         "ALL",
	ReduceWindowFunctionANY:         "ANY",
}

var EnumValuesReduceWindowFunction = map[string]ReduceWindowFunction{
	"UNSUPPORTED": ReduceWindowFunctionUNSUPPORTED,
	"ADD":         ReduceWindowFunctionADD,
	"MUL":         ReduceWindowFunctionMUL,
	"MINIMUM":     ReduceWindowFunctionMINIMUM,
	"MAXIMUM":     ReduceWindowFunctionMAXIMUM,
	"ALL":         ReduceWindowFunctionALL,
	"ANY":         ReduceWindowFunctionANY,
}

func (v ReduceWindowFunction) String() string {
	if s, ok := EnumNamesReduceWindowFunction[v]; ok {
		return s
	}
	return "ReduceWindowFunction(" + strconv.FormatInt(int64(v), 10) + ")"
}
