// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import "strconv"

type RngAlgorithm int8

const (
	RngAlgorithmDEFAULT  RngAlgorithm = 0
	RngAlgorithmPHILOX   RngAlgorithm = 1
	RngAlgorithmTHREEFRY RngAlgorithm = 2
)

var EnumNamesRngAlgorithm = map[RngAlgorithm]string{
	RngAlgorithmDEFAULT:  "DEFAULT",
	RngAlgorithmPHILOX:   "PHILOX",
	RngAlgorithmTHREEFRY: "THREEFRY",
}

var EnumValuesRngAlgorithm = map[string]RngAlgorithm{
	"DEFAULT":  RngAlgorithmDEFAULT,
	"PHILOX":   RngAlgorithmPHILOX,
	"THREEFRY": RngAlgorithmTHREEFRY,
}

func (v RngAlgorithm) String() string {
	if s, ok := EnumNamesRngAlgorithm[v]; ok {
		return s
	}
	return "RngAlgorithm(" + strconv.FormatInt(int64(v), 10) + ")"
}
