// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ScatterNdOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsScatterNdOptions(buf []byte, offset flatbuffers.UOffsetT) *ScatterNdOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ScatterNdOptions{}
	x.Init(buf, n+offset)
	return x
}

func FinishScatterNdOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsScatterNdOptions(buf []byte, offset flatbuffers.UOffsetT) *ScatterNdOptions {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ScatterNdOptions{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedScatterNdOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ScatterNdOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ScatterNdOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func ScatterNdOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func ScatterNdOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
