// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SliceOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsSliceOptions(buf []byte, offset flatbuffers.UOffsetT) *SliceOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SliceOptions{}
	x.Init(buf, n+offset)
	return x
}

func FinishSliceOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSliceOptions(buf []byte, offset flatbuffers.UOffsetT) *SliceOptions {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SliceOptions{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSliceOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SliceOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SliceOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func SliceOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func SliceOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
