// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SquaredDifferenceOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsSquaredDifferenceOptions(buf []byte, offset flatbuffers.UOffsetT) *SquaredDifferenceOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SquaredDifferenceOptions{}
	x.Init(buf, n+offset)
	return x
}

func FinishSquaredDifferenceOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSquaredDifferenceOptions(buf []byte, offset flatbuffers.UOffsetT) *SquaredDifferenceOptions {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SquaredDifferenceOptions{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSquaredDifferenceOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SquaredDifferenceOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SquaredDifferenceOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func SquaredDifferenceOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func SquaredDifferenceOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
