// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StablehloWhileOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsStablehloWhileOptions(buf []byte, offset flatbuffers.UOffsetT) *StablehloWhileOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StablehloWhileOptions{}
	x.Init(buf, n+offset)
	return x
}

func FinishStablehloWhileOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStablehloWhileOptions(buf []byte, offset flatbuffers.UOffsetT) *StablehloWhileOptions {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StablehloWhileOptions{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStablehloWhileOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StablehloWhileOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StablehloWhileOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StablehloWhileOptions) CondSubgraphIndex() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StablehloWhileOptions) MutateCondSubgraphIndex(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *StablehloWhileOptions) BodySubgraphIndex() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StablehloWhileOptions) MutateBodySubgraphIndex(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func StablehloWhileOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func StablehloWhileOptionsAddCondSubgraphIndex(builder *flatbuffers.Builder, condSubgraphIndex int32) {
	builder.PrependInt32Slot(0, condSubgraphIndex, 0)
}
func StablehloWhileOptionsAddBodySubgraphIndex(builder *flatbuffers.Builder, bodySubgraphIndex int32) {
	builder.PrependInt32Slot(1, bodySubgraphIndex, 0)
}
func StablehloWhileOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
