// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import "strconv"

type StablehloComparisonType uint32

const (
	StablehloComparisonTypeSTABLEHLO_COMPARISON_TYPE_NOTYPE            StablehloComparisonType = 0
	StablehloComparisonTypeSTABLEHLO_COMPARISON_TYPE_FLOAT             StablehloComparisonType = 1
	StablehloComparisonTypeSTABLEHLO_COMPARISON_TYPE_FLOAT_TOTAL_ORDER StablehloComparisonType = 2
	StablehloComparisonTypeSTABLEHLO_COMPARISON_TYPE_SIGNED            StablehloComparisonType = 3
	StablehloComparisonTypeSTABLEHLO_COMPARISON_TYPE_UNSIGNED          StablehloComparisonType = 4
)

var EnumNamesStablehloComparisonType = map[StablehloComparisonType]string{
	StablehloComparisonTypeSTABLEHLO_COMPARISON_TYPE_NOTYPE:            "STABLEHLO_COMPARISON_TYPE_NOTYPE",
	StablehloComparisonTypeSTABLEHLO_COMPARISON_TYPE_FLOAT:             "STABLEHLO_COMPARISON_TYPE_FLOAT",
	StablehloComparisonTypeSTABLEHLO_COMPARISON_TYPE_FLOAT_TOTAL_ORDER: "STABLEHLO_COMPARISON_TYPE_FLOAT_TOTAL_ORDER",
	StablehloComparisonTypeSTABLEHLO_COMPARISON_TYPE_SIGNED:            "STABLEHLO_COMPARISON_TYPE_SIGNED",
	StablehloComparisonTypeSTABLEHLO_COMPARISON_TYPE_UNSIGNED:          "STABLEHLO_COMPARISON_TYPE_UNSIGNED",
}

var EnumValuesStablehloComparisonType = map[string]StablehloComparisonType{
	"STABLEHLO_COMPARISON_TYPE_NOTYPE":            StablehloComparisonTypeSTABLEHLO_COMPARISON_TYPE_NOTYPE,
	"STABLEHLO_COMPARISON_TYPE_FLOAT":             StablehloComparisonTypeSTABLEHLO_COMPARISON_TYPE_FLOAT,
	"STABLEHLO_COMPARISON_TYPE_FLOAT_TOTAL_ORDER": StablehloComparisonTypeSTABLEHLO_COMPARISON_TYPE_FLOAT_TOTAL_ORDER,
	"STABLEHLO_COMPARISON_TYPE_SIGNED":            StablehloComparisonTypeSTABLEHLO_COMPARISON_TYPE_SIGNED,
	"STABLEHLO_COMPARISON_TYPE_UNSIGNED":          StablehloComparisonTypeSTABLEHLO_COMPARISON_TYPE_UNSIGNED,
}

func (v StablehloComparisonType) String() string {
	if s, ok := EnumNamesStablehloComparisonType[v]; ok {
		return s
	}
	return "StablehloComparisonType(" + strconv.FormatInt(int64(v), 10) + ")"
}
