// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StablehloSortOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsStablehloSortOptions(buf []byte, offset flatbuffers.UOffsetT) *StablehloSortOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StablehloSortOptions{}
	x.Init(buf, n+offset)
	return x
}

func FinishStablehloSortOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStablehloSortOptions(buf []byte, offset flatbuffers.UOffsetT) *StablehloSortOptions {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StablehloSortOptions{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStablehloSortOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StablehloSortOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StablehloSortOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StablehloSortOptions) Dimension() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StablehloSortOptions) MutateDimension(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *StablehloSortOptions) IsStable() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *StablehloSortOptions) MutateIsStable(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func (rcv *StablehloSortOptions) ComparatorSubgraphIndex() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StablehloSortOptions) MutateComparatorSubgraphIndex(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func StablehloSortOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func StablehloSortOptionsAddDimension(builder *flatbuffers.Builder, dimension int64) {
	builder.PrependInt64Slot(0, dimension, 0)
}
func StablehloSortOptionsAddIsStable(builder *flatbuffers.Builder, isStable bool) {
	builder.PrependBoolSlot(1, isStable, false)
}
func StablehloSortOptionsAddComparatorSubgraphIndex(builder *flatbuffers.Builder, comparatorSubgraphIndex int32) {
	builder.PrependInt32Slot(2, comparatorSubgraphIndex, 0)
}
func StablehloSortOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
