// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StablehloIotaOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsStablehloIotaOptions(buf []byte, offset flatbuffers.UOffsetT) *StablehloIotaOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StablehloIotaOptions{}
	x.Init(buf, n+offset)
	return x
}

func FinishStablehloIotaOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStablehloIotaOptions(buf []byte, offset flatbuffers.UOffsetT) *StablehloIotaOptions {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StablehloIotaOptions{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStablehloIotaOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StablehloIotaOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StablehloIotaOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StablehloIotaOptions) IotaDimension() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StablehloIotaOptions) MutateIotaDimension(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func StablehloIotaOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func StablehloIotaOptionsAddIotaDimension(builder *flatbuffers.Builder, iotaDimension int64) {
	builder.PrependInt64Slot(0, iotaDimension, 0)
}
func StablehloIotaOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
