// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StablehloConcatenateOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsStablehloConcatenateOptions(buf []byte, offset flatbuffers.UOffsetT) *StablehloConcatenateOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StablehloConcatenateOptions{}
	x.Init(buf, n+offset)
	return x
}

func FinishStablehloConcatenateOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStablehloConcatenateOptions(buf []byte, offset flatbuffers.UOffsetT) *StablehloConcatenateOptions {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StablehloConcatenateOptions{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStablehloConcatenateOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StablehloConcatenateOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StablehloConcatenateOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StablehloConcatenateOptions) Dimension() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StablehloConcatenateOptions) MutateDimension(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func StablehloConcatenateOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func StablehloConcatenateOptionsAddDimension(builder *flatbuffers.Builder, dimension int64) {
	builder.PrependInt64Slot(0, dimension, 0)
}
func StablehloConcatenateOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
