// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StablehloRngBitGeneratorOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsStablehloRngBitGeneratorOptions(buf []byte, offset flatbuffers.UOffsetT) *StablehloRngBitGeneratorOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StablehloRngBitGeneratorOptions{}
	x.Init(buf, n+offset)
	return x
}

func FinishStablehloRngBitGeneratorOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStablehloRngBitGeneratorOptions(buf []byte, offset flatbuffers.UOffsetT) *StablehloRngBitGeneratorOptions {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StablehloRngBitGeneratorOptions{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStablehloRngBitGeneratorOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StablehloRngBitGeneratorOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StablehloRngBitGeneratorOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StablehloRngBitGeneratorOptions) Algorithm() RngAlgorithm {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return RngAlgorithm(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *StablehloRngBitGeneratorOptions) MutateAlgorithm(n RngAlgorithm) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func StablehloRngBitGeneratorOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func StablehloRngBitGeneratorOptionsAddAlgorithm(builder *flatbuffers.Builder, algorithm RngAlgorithm) {
	builder.PrependInt8Slot(0, int8(algorithm), 0)
}
func StablehloRngBitGeneratorOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
