// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StablehloBroadcastInDimOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsStablehloBroadcastInDimOptions(buf []byte, offset flatbuffers.UOffsetT) *StablehloBroadcastInDimOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StablehloBroadcastInDimOptions{}
	x.Init(buf, n+offset)
	return x
}

func FinishStablehloBroadcastInDimOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStablehloBroadcastInDimOptions(buf []byte, offset flatbuffers.UOffsetT) *StablehloBroadcastInDimOptions {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StablehloBroadcastInDimOptions{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStablehloBroadcastInDimOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StablehloBroadcastInDimOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StablehloBroadcastInDimOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StablehloBroadcastInDimOptions) BroadcastDimensions(j int) int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetInt64(a + flatbuffers.UOffsetT(j*8))
	}
	return 0
}

func (rcv *StablehloBroadcastInDimOptions) BroadcastDimensionsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *StablehloBroadcastInDimOptions) MutateBroadcastDimensions(j int, n int64) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateInt64(a+flatbuffers.UOffsetT(j*8), n)
	}
	return false
}

func StablehloBroadcastInDimOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func StablehloBroadcastInDimOptionsAddBroadcastDimensions(builder *flatbuffers.Builder, broadcastDimensions flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(broadcastDimensions), 0)
}
func StablehloBroadcastInDimOptionsStartBroadcastDimensionsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 8)
}
func StablehloBroadcastInDimOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
