// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StablehloDynamicSliceOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsStablehloDynamicSliceOptions(buf []byte, offset flatbuffers.UOffsetT) *StablehloDynamicSliceOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StablehloDynamicSliceOptions{}
	x.Init(buf, n+offset)
	return x
}

func FinishStablehloDynamicSliceOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStablehloDynamicSliceOptions(buf []byte, offset flatbuffers.UOffsetT) *StablehloDynamicSliceOptions {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StablehloDynamicSliceOptions{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStablehloDynamicSliceOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StablehloDynamicSliceOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StablehloDynamicSliceOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StablehloDynamicSliceOptions) SliceSizes(j int) int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetInt64(a + flatbuffers.UOffsetT(j*8))
	}
	return 0
}

func (rcv *StablehloDynamicSliceOptions) SliceSizesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *StablehloDynamicSliceOptions) MutateSliceSizes(j int, n int64) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateInt64(a+flatbuffers.UOffsetT(j*8), n)
	}
	return false
}

func StablehloDynamicSliceOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func StablehloDynamicSliceOptionsAddSliceSizes(builder *flatbuffers.Builder, sliceSizes flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(sliceSizes), 0)
}
func StablehloDynamicSliceOptionsStartSliceSizesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 8)
}
func StablehloDynamicSliceOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
