// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import "strconv"

type StablehloPrecisionConfig uint32

const (
	StablehloPrecisionConfigDEFAULT StablehloPrecisionConfig = 0
	StablehloPrecisionConfigHIGH    StablehloPrecisionConfig = 1
	StablehloPrecisionConfigHIGHEST StablehloPrecisionConfig = 2
)

var EnumNamesStablehloPrecisionConfig = map[StablehloPrecisionConfig]string{
	StablehloPrecisionConfigDEFAULT: "DEFAULT",
	StablehloPrecisionConfigHIGH:    "HIGH",
	StablehloPrecisionConfigHIGHEST: "HIGHEST",
}

var EnumValuesStablehloPrecisionConfig = map[string]StablehloPrecisionConfig{
	"DEFAULT": StablehloPrecisionConfigDEFAULT,
	"HIGH":    StablehloPrecisionConfigHIGH,
	"HIGHEST": StablehloPrecisionConfigHIGHEST,
}

func (v StablehloPrecisionConfig) String() string {
	if s, ok := EnumNamesStablehloPrecisionConfig[v]; ok {
		return s
	}
	return "StablehloPrecisionConfig(" + strconv.FormatInt(int64(v), 10) + ")"
}
