// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StablehloTransposeOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsStablehloTransposeOptions(buf []byte, offset flatbuffers.UOffsetT) *StablehloTransposeOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StablehloTransposeOptions{}
	x.Init(buf, n+offset)
	return x
}

func FinishStablehloTransposeOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStablehloTransposeOptions(buf []byte, offset flatbuffers.UOffsetT) *StablehloTransposeOptions {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StablehloTransposeOptions{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStablehloTransposeOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StablehloTransposeOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StablehloTransposeOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StablehloTransposeOptions) Permutation(j int) int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetInt64(a + flatbuffers.UOffsetT(j*8))
	}
	return 0
}

func (rcv *StablehloTransposeOptions) PermutationLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *StablehloTransposeOptions) MutatePermutation(j int, n int64) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateInt64(a+flatbuffers.UOffsetT(j*8), n)
	}
	return false
}

func StablehloTransposeOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func StablehloTransposeOptionsAddPermutation(builder *flatbuffers.Builder, permutation flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(permutation), 0)
}
func StablehloTransposeOptionsStartPermutationVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 8)
}
func StablehloTransposeOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
