// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TransposeOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsTransposeOptions(buf []byte, offset flatbuffers.UOffsetT) *TransposeOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TransposeOptions{}
	x.Init(buf, n+offset)
	return x
}

func FinishTransposeOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTransposeOptions(buf []byte, offset flatbuffers.UOffsetT) *TransposeOptions {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TransposeOptions{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTransposeOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TransposeOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TransposeOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func TransposeOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func TransposeOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
