// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UnsortedSegmentProdOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsUnsortedSegmentProdOptions(buf []byte, offset flatbuffers.UOffsetT) *UnsortedSegmentProdOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UnsortedSegmentProdOptions{}
	x.Init(buf, n+offset)
	return x
}

func FinishUnsortedSegmentProdOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsUnsortedSegmentProdOptions(buf []byte, offset flatbuffers.UOffsetT) *UnsortedSegmentProdOptions {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UnsortedSegmentProdOptions{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedUnsortedSegmentProdOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *UnsortedSegmentProdOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UnsortedSegmentProdOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func UnsortedSegmentProdOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func UnsortedSegmentProdOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
