// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UnsortedSegmentMinOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsUnsortedSegmentMinOptions(buf []byte, offset flatbuffers.UOffsetT) *UnsortedSegmentMinOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UnsortedSegmentMinOptions{}
	x.Init(buf, n+offset)
	return x
}

func FinishUnsortedSegmentMinOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsUnsortedSegmentMinOptions(buf []byte, offset flatbuffers.UOffsetT) *UnsortedSegmentMinOptions {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UnsortedSegmentMinOptions{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedUnsortedSegmentMinOptionsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *UnsortedSegmentMinOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UnsortedSegmentMinOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func UnsortedSegmentMinOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func UnsortedSegmentMinOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
