#include <stdio.h>
#include <stdint.h>
#include "audio_preprocessor_operators.h"

uint8_t *AUDIO_PREPROCESSOR_get_operator(const AUDIO_PREPROCESSOR_Operators *operators, int index){
    uint32_t sizes[22] = {0,
sizeof(operators->operator_0),
sizeof(operators->operator_1) + sizeof(operators->operator_0),
sizeof(operators->operator_2) + sizeof(operators->operator_0) + sizeof(operators->operator_1),
sizeof(operators->operator_3) + sizeof(operators->operator_0) + sizeof(operators->operator_1) + sizeof(operators->operator_2),
sizeof(operators->operator_4) + sizeof(operators->operator_0) + sizeof(operators->operator_1) + sizeof(operators->operator_2) + sizeof(operators->operator_3),
sizeof(operators->operator_5) + sizeof(operators->operator_0) + sizeof(operators->operator_1) + sizeof(operators->operator_2) + sizeof(operators->operator_3) + sizeof(operators->operator_4),
sizeof(operators->operator_6) + sizeof(operators->operator_0) + sizeof(operators->operator_1) + sizeof(operators->operator_2) + sizeof(operators->operator_3) + sizeof(operators->operator_4) + sizeof(operators->operator_5),
sizeof(operators->operator_7) + sizeof(operators->operator_0) + sizeof(operators->operator_1) + sizeof(operators->operator_2) + sizeof(operators->operator_3) + sizeof(operators->operator_4) + sizeof(operators->operator_5) + sizeof(operators->operator_6),
sizeof(operators->operator_8) + sizeof(operators->operator_0) + sizeof(operators->operator_1) + sizeof(operators->operator_2) + sizeof(operators->operator_3) + sizeof(operators->operator_4) + sizeof(operators->operator_5) + sizeof(operators->operator_6) + sizeof(operators->operator_7),
sizeof(operators->operator_9) + sizeof(operators->operator_0) + sizeof(operators->operator_1) + sizeof(operators->operator_2) + sizeof(operators->operator_3) + sizeof(operators->operator_4) + sizeof(operators->operator_5) + sizeof(operators->operator_6) + sizeof(operators->operator_7) + sizeof(operators->operator_8),
sizeof(operators->operator_10) + sizeof(operators->operator_0) + sizeof(operators->operator_1) + sizeof(operators->operator_2) + sizeof(operators->operator_3) + sizeof(operators->operator_4) + sizeof(operators->operator_5) + sizeof(operators->operator_6) + sizeof(operators->operator_7) + sizeof(operators->operator_8) + sizeof(operators->operator_9),
sizeof(operators->operator_11) + sizeof(operators->operator_0) + sizeof(operators->operator_1) + sizeof(operators->operator_2) + sizeof(operators->operator_3) + sizeof(operators->operator_4) + sizeof(operators->operator_5) + sizeof(operators->operator_6) + sizeof(operators->operator_7) + sizeof(operators->operator_8) + sizeof(operators->operator_9) + sizeof(operators->operator_10),
sizeof(operators->operator_12) + sizeof(operators->operator_0) + sizeof(operators->operator_1) + sizeof(operators->operator_2) + sizeof(operators->operator_3) + sizeof(operators->operator_4) + sizeof(operators->operator_5) + sizeof(operators->operator_6) + sizeof(operators->operator_7) + sizeof(operators->operator_8) + sizeof(operators->operator_9) + sizeof(operators->operator_10) + sizeof(operators->operator_11),
sizeof(operators->operator_13) + sizeof(operators->operator_0) + sizeof(operators->operator_1) + sizeof(operators->operator_2) + sizeof(operators->operator_3) + sizeof(operators->operator_4) + sizeof(operators->operator_5) + sizeof(operators->operator_6) + sizeof(operators->operator_7) + sizeof(operators->operator_8) + sizeof(operators->operator_9) + sizeof(operators->operator_10) + sizeof(operators->operator_11) + sizeof(operators->operator_12),
sizeof(operators->operator_14) + sizeof(operators->operator_0) + sizeof(operators->operator_1) + sizeof(operators->operator_2) + sizeof(operators->operator_3) + sizeof(operators->operator_4) + sizeof(operators->operator_5) + sizeof(operators->operator_6) + sizeof(operators->operator_7) + sizeof(operators->operator_8) + sizeof(operators->operator_9) + sizeof(operators->operator_10) + sizeof(operators->operator_11) + sizeof(operators->operator_12) + sizeof(operators->operator_13),
sizeof(operators->operator_15) + sizeof(operators->operator_0) + sizeof(operators->operator_1) + sizeof(operators->operator_2) + sizeof(operators->operator_3) + sizeof(operators->operator_4) + sizeof(operators->operator_5) + sizeof(operators->operator_6) + sizeof(operators->operator_7) + sizeof(operators->operator_8) + sizeof(operators->operator_9) + sizeof(operators->operator_10) + sizeof(operators->operator_11) + sizeof(operators->operator_12) + sizeof(operators->operator_13) + sizeof(operators->operator_14),
sizeof(operators->operator_16) + sizeof(operators->operator_0) + sizeof(operators->operator_1) + sizeof(operators->operator_2) + sizeof(operators->operator_3) + sizeof(operators->operator_4) + sizeof(operators->operator_5) + sizeof(operators->operator_6) + sizeof(operators->operator_7) + sizeof(operators->operator_8) + sizeof(operators->operator_9) + sizeof(operators->operator_10) + sizeof(operators->operator_11) + sizeof(operators->operator_12) + sizeof(operators->operator_13) + sizeof(operators->operator_14) + sizeof(operators->operator_15),
sizeof(operators->operator_17) + sizeof(operators->operator_0) + sizeof(operators->operator_1) + sizeof(operators->operator_2) + sizeof(operators->operator_3) + sizeof(operators->operator_4) + sizeof(operators->operator_5) + sizeof(operators->operator_6) + sizeof(operators->operator_7) + sizeof(operators->operator_8) + sizeof(operators->operator_9) + sizeof(operators->operator_10) + sizeof(operators->operator_11) + sizeof(operators->operator_12) + sizeof(operators->operator_13) + sizeof(operators->operator_14) + sizeof(operators->operator_15) + sizeof(operators->operator_16),
sizeof(operators->operator_18) + sizeof(operators->operator_0) + sizeof(operators->operator_1) + sizeof(operators->operator_2) + sizeof(operators->operator_3) + sizeof(operators->operator_4) + sizeof(operators->operator_5) + sizeof(operators->operator_6) + sizeof(operators->operator_7) + sizeof(operators->operator_8) + sizeof(operators->operator_9) + sizeof(operators->operator_10) + sizeof(operators->operator_11) + sizeof(operators->operator_12) + sizeof(operators->operator_13) + sizeof(operators->operator_14) + sizeof(operators->operator_15) + sizeof(operators->operator_16) + sizeof(operators->operator_17),
sizeof(operators->operator_19) + sizeof(operators->operator_0) + sizeof(operators->operator_1) + sizeof(operators->operator_2) + sizeof(operators->operator_3) + sizeof(operators->operator_4) + sizeof(operators->operator_5) + sizeof(operators->operator_6) + sizeof(operators->operator_7) + sizeof(operators->operator_8) + sizeof(operators->operator_9) + sizeof(operators->operator_10) + sizeof(operators->operator_11) + sizeof(operators->operator_12) + sizeof(operators->operator_13) + sizeof(operators->operator_14) + sizeof(operators->operator_15) + sizeof(operators->operator_16) + sizeof(operators->operator_17) + sizeof(operators->operator_18),
sizeof(operators->operator_20) + sizeof(operators->operator_0) + sizeof(operators->operator_1) + sizeof(operators->operator_2) + sizeof(operators->operator_3) + sizeof(operators->operator_4) + sizeof(operators->operator_5) + sizeof(operators->operator_6) + sizeof(operators->operator_7) + sizeof(operators->operator_8) + sizeof(operators->operator_9) + sizeof(operators->operator_10) + sizeof(operators->operator_11) + sizeof(operators->operator_12) + sizeof(operators->operator_13) + sizeof(operators->operator_14) + sizeof(operators->operator_15) + sizeof(operators->operator_16) + sizeof(operators->operator_17) + sizeof(operators->operator_18) + sizeof(operators->operator_19)};
    return (uint8_t *)operators + sizes[index];
}

